### ISSUE TITLE
Incompatibility with anki-2.1.21beta1

### ISSUE THREAD

**Issue by ghost** [lovac42/LifeDrain_EndGames#5]
As mentioned by the author of Lifedrain [here](https://github.com/Yutsuten/anki-lifedrain/issues/48), the following error in anki-2.1.21beta1 is due to pomodoro timer
To reproduce let the timer tick down to the end.
Debug info:
Anki 2.1.21 (683b7983) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-19 10:11:29

Caught exception:
Traceback (most recent call last):
File "aqt\progress.py", line 76, in handler
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 584, in timerTrigger
lifeDrain.deckBarManager.recover(False, 0.1)
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 548, in recover
runHook('LifeDrain.gameOver')
File "lib\site-packages\anki\hooks.py", line 555, in runHook
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\PomodoroTimer\lifedrain_pomodoroTimer.py", line 123, in pomodoroTimer
mw.web.stdHtml(TOMATO_ASCII%(msg,time),
File "aqt\webview.py", line 333, in stdHtml
TypeError: can only concatenate list (not "str") to list

**Comment by lovac42** [comment]
Every 3 days, something breaks. I'm not jumping on the 2.1.2x bandwagon.

**Comment by ghost** [comment]
Admittedly 21 introduced far more bugs than features.

**Comment by lovac42** [comment]
It has been updated, enjoy the tomato.

**Comment by ghost** [comment]
Thanks a ton lovac. This is a huge timesaver for me.
